name: Haber Botu Calistir
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  haber_paylas:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Eski Kalintilari Sil ve Yukle
        run: |
          pip uninstall google-generativeai -y
          pip install -r requirements.txt
      - name: Botu Calistir
        run: python haberci.py
